---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-centos-6",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "centos-6"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-centos-7",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "centos-7"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-debian-8",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "debian-8"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-debian-9",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "debian-9"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-ubuntu-1404",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "ubuntu-1404"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "depends_on": [
      "run-shellcheck"
   ],
   "kind": "pipeline",
   "name": "build-ubuntu-1804",
   "steps": [
      {
         "image": "saltstack/drone-plugin-kitchen",
         "name": "build",
         "privileged": true,
         "settings": {
            "requirements": "tests/requirements.txt",
            "target": "ubuntu-1804"
         },
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
{
   "kind": "pipeline",
   "name": "run-shellcheck",
   "steps": [
      {
         "commands": [
            "shellcheck -s sh -f checkstyle bootstrap-salt.sh"
         ],
         "image": "koalaman/shellcheck-alpine",
         "name": "shellcheck",
         "when": {
            "event": [
               "pull_request"
            ]
         }
      }
   ]
}
---
kind: signature
hmac: e0f575abc8248a3efe3291836aaee209aac496312196dc8289c4e5abc8268c3a

...
