---
kind: pipeline
name: build-centos-6

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: centos-6
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-centos-7

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: centos-7
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-debian-8

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: debian-8
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-debian-9

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: debian-9
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-ubuntu-1404

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: ubuntu-1404
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-ubuntu-1804

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    requirements: tests/requirements.txt
    target: ubuntu-1804
  privileged: true
  when:
    event:
    - pull_request

depends_on:
- run-shellcheck

---
kind: pipeline
name: run-shellcheck

platform:
  os: linux
  arch: amd64

steps:
- name: run-shellcheck
  image: koalaman/shellcheck-alpine
  commands:
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh
  when:
    event:
    - pull_request

---
kind: signature
hmac: 3932ad0ad24dfbc51ac7367295fbd3c95288dc79bfb12246269965f9a9965ae4

...
