---
kind: pipeline
name: run-shellcheck

steps:
- name: build
  image: koalaman/shellcheck-alpine
  commands:
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh

---
kind: pipeline
name: build-centos6

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: centos-6
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-centos7

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: centos-7
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-amazon1

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: amazon1
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-amazon2

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: amazon2
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-debian8

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: debian8
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-debian9

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: debian9
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-fedora

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: fedora
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-opensuse

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: opensuse
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-ubuntu1604

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: ubuntu1604
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck

---
kind: pipeline
name: build-ubuntu1804

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  failure: ignore
  settings:
    target: ubuntu1804
    requirements: tests/requirements.txt

depends_on:
- run-shellcheck



---
kind: signature
hmac: 32411e880077b35a310059229f194fd9a8e0fe7a10ec82d556e842d197349228

...
