before_install:
  - sudo apt-get update && sudo apt-get install
  - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
  - pip install unittest-xml-reporting

script:
  - sudo python tests/runtests.py -vv

notifications:
  irc:
    channels: "irc.freenode.org#salt-devel"
    on_success: change
    on_failure: change
