language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
  - PLATFORM=fedora
  - PLATFORM=centos-7
  - PLATFORM=centos-6
  - PLATFORM=ubuntu-1804
  - PLATFORM=ubuntu-1604
  - PLATFORM=ubuntu-1404
  - PLATFORM=debian-8
  - PLATFORM=debian-9
  - PLATFORM=arch
  - PLATFORM=opensuse

sudo: true
dist: trusty

before_install:
  - pip install --user -r tests/requirements.txt

script:
  # Check shell scripts
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh
  # Run test-kitchen with docker driver:
  - bundle exec kitchen create -l warn -c 6 "$PLATFORM"
  - bundle exec kitchen converge "$PLATFORM"
  - bundle exec kitchen verify "$PLATFORM"

after_script:
  - bundle exec kitchen list $PLATFORM
  - bundle exec kitchen destriy "$PLATFORM"
