language: ruby

services:
  - docker

addons:
  apt:
    packages:
    - curl
    - git
    - shellcheck
    - python-pip

rvm:
  - ruby

env:
  matrix:
    - SUITE=py2-git-20177
    - SUITE=py2-git-20183
    - SUITE=py2-git-fluorine
    - SUITE=py2-git-develop
    - SUITE=py2-stable-20177
    - SUITE=py2-stable-20183


sudo: true
dist: trusty

before_install:
  - pip install --user -r tests/requirements.txt

script:
  # Check shell scripts
  - shellcheck -s sh -f checkstyle bootstrap-salt.sh
  # Run test-kitchen with docker driver:
  - bundle exec kitchen create -l warn -c 10 "$SUITE"
  - bundle exec kitchen converge "$SUITE"
  - bundle exec kitchen verify "$SUITE"

after_script:
  - bundle exec kitchen list $SUITE
  - bundle exec kitchen destriy "$SUITE"
